version: '3.8'

services:
  postgres:
    container_name: newspaper_db
    image: postgres:16.0-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: newspaper
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    container_name: newspaper_backend
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    command: bash -c "cd /app && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      - .env
    volumes:
      - .:/app
    depends_on: 
      - postgres
    ports:
      - "8000:8000"

  frontend:
    container_name: newspaper_web
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    command: "npm run dev"
    volumes:
      - .:/app
    depends_on: 
      - backend
      - postgres
    ports:
      - "3000:3000"

volumes:
  pgdata: